### ISSUE TITLE
Flutter?

### ISSUE THREAD

**Issue by trymeouteh** [sweakpl/qralarm-android#10]
I noticed you first made this app in Java and remade it now in Kotlin. However I would like to suggest making this app in Flutter. The reason is because flutter allows you to compile the app for Android, iOS, Windows, MacoS and Linux! Flutter uses Dart and is growing in popularity.

I know this would be the 3rd time you made this app, but your app can be installed on any device and used by anyone and not limited to Android users.

**Comment by magnus-ISU** [comment]
Does Flutter have APIs for alarms?

**Comment by sweakpl** [comment]
Thank You for suggestion, but I'm not going to be rewriting the app in Flutter anytime soon. But if You want, You're free to modify nad/or port QRAlarm with any tools You want.
