### ISSUE TITLE
Feature request: Note how many hours + minutes until the alarm will go off, when it is set.

### ISSUE THREAD

**Issue by magnus-ISU** [sweakpl/qralarm-android#13]
This is what the default alarm app does, and I think it is a nice feature.

**Comment by domportera** [comment]
This is included in my pull request, so should be available as soon as sweakpl gets to it.

If they decide to yeet it (it's my first time doing the whole kotlin/android thing) you can get a debug build I made [here](https://github.com/domportera/qralarm-android/releases/tag/v1.3.1)
