### ISSUE TITLE
Time setting must be "flingable"

### ISSUE THREAD

**Issue by Marmotian** [sweakpl/qralarm-android#14]
Setting the alarm is very motion intensive because you can't use a "fling" gesture to cause the setting to change quickly. The worst case (changing the minutes by 30) takes a minimum of 8 full-screen swipes on my phone.

Or, make it so you can tap the numbers to open a keyboard entry mode. Or both.

**Comment by domportera** [comment]
I tried forking and messing with this and found some difficulties in getting the "fling" to work properly or respond to different parameters in a predictable and intuitive way.

However in the meantime I just sped up the Minutes control. it's a little bit unwieldy, but imo it's preferred for the time being. I made a thoroughly under-tested build you can grab [here](https://github.com/domportera/qralarm-android/releases/tag/faster-minutes) if you're itching for it, but I can't say I recommend it. I'll be using it though.

I'm wondering what @sweakpl thinks of [this sort of architecture](https://github.com/domportera/qralarm-android/commit/4dc1bc26b0792b3fefdf11098bfe8717415db00a) for these sorts of changes. It's basically my first time in kotlin/android studio so forgive me for being somewhat crude

**Comment by sweakpl** [comment]
@domportera I've tried implementing the fling but it's been a harder task than I though it should be. The code responsible for the time picker is a modification of this gist: https://gist.github.com/vganin/a9a84653a9f48a2d669910fbd48e32d5

There are some suggestions from the author there but still, I couldn't find a way to get that functionality or I've just spent too little time on it.

**Comment by domportera** [comment]
I haven't gotten into depth of that code, but I submitted a pull request for an optional speed increase. Its presentation when the speed is increased is a bit janky, but it works.
