### ISSUE TITLE
Set and save multiple clocks and QrCodes

### ISSUE THREAD

**Issue by RZHSSNZDH** [sweakpl/qralarm-android#19]
Hello. Thank you for the app. It would be very better if there was a feature to set more than one clock and also Qr Codes. For example I want to have an alarm in 6 pm with Qr Code 1 and another one in 6 am with Qr Code 2.

**Comment by sweakpl** [comment]
Interesting idea! With current structure of the app this would be difficult to implement though. I will keep this idea in mind 👍
