### ISSUE TITLE
Option to make the alarm persistent

### ISSUE THREAD

**Issue by BloodRaven0** [sweakpl/qralarm-android#2]
I think there should be an option to keep the alarm after you turn it off with the qr code, so you don't have to "start" it again each day, because you might forget.

**Comment by sweakpl** [comment]
Hey, thanks for the suggestion!

While creating the app, I thought that persistent alarm could be problematic with QRAlarm - the user might leave the alarm scheduled and e.g. wake up in a different place than the place where their QR code is which in turn would mean that the alarm would not be possible to turn off (at least in theory ;)).

This is why I've decided to leave it as it is now - the user having control over the alarm that can go off not later than 24 hours from the moment of scheduling. This should at least try to prevent the mentioned situation.

But possibly in the future I might try to implement this functionality.

Thank You fot the feedback!

**Comment by BloodRaven0** [comment]
I had not thought of that 😅

You could put a warning on the "persistent alarms" option that warns users of this situation, perhaps recommending they print out a spare qr code they could carry in their wallet or whatnot.

Another option would be to have an alternate (but not easier) way to turn the alarm off, but I have no idea what that could be, and it might go outside the scope you have for the app (for example solving math problems or something like that).

**Comment by magnus-ISU** [comment]
You can turn off the alarm by uninstalling the app as well I believe.

I hope this is eventually added, but I don't think its high priority as its pretty easy to tap the 'set' button after waking up.

**Comment by lmgarret** [comment]
What about setting a SSID for which the alarm can be recurring, and disabled if not connected to this specific wifi? Although for people putting their devices in airplane mode while sleeping this might get tricky

**Comment by sweakpl** [comment]
@lmgarret That's interesting but quite complex idea 😅 First, listening to connectivity changes requires the app to work constantly in the background service which is always very vulnerable to wrong background work settings and the system itself. Secondly, an option like this is VERY specific to some users (e.g. some might not have wifi enabled all the time or at all). Third thing - the option might be confusing to some people, especially for an app which I wanted to be an as simple as possible QR code alarm app.
