### ISSUE TITLE
Can be force closed

### ISSUE THREAD

**Issue by Barmem** [sweakpl/qralarm-android#20]
Maybe make it autolaunch?

**Comment by magnus-ISU** [comment]
It can also be uninstalled. At that point the user is being hostile to the application, and apps shouldn't try to implement hacks to work around being killed that way.

**Comment by Barmem** [comment]
on my phone force closing is literally holding back button

**Comment by sweakpl** [comment]
As @magnus-ISU pointed out, the app cannot work against the system and if the user makes the app force-stop then it won't be re-launched without the user explicitly doing so. *QRAlarm* has a way of detecting if the app was improperly shutdown but that functionality is working only if the user re-launches the app after shutdown and is there to ensure the data consistency to prevent weird UI behavior.

@Barmem if your phone has some strict policies about application lifecycle then please, refer to the *QRAlarm Guide* in the settings of the app. There is a link to a [site](https://dontkillmyapp.com/) that might help you mitigate the behavior of your phone.
