### ISSUE TITLE
Add availability to stop alarm without scanning

### ISSUE THREAD

**Issue by RZHSSNZDH** [sweakpl/qralarm-android#22]
In my opinion it is logical to can stop the alarm without need to scan QrCode if the time right now has much distance to alarm's time. For example if there is 1 hour distance from now to alarm's time, I should can to stop the alarm without scanning. I do not know the suitable time for setting this tip, but this tip is important in my idea.

**Comment by sweakpl** [comment]
The issue https://github.com/sweakpl/qralarm-android/issues/15 has touched upon this topic already, but You have a different take with the "QR alarm timeout". I think I will reconsider the idea and maybe it will end up in the application in the future.
