### ISSUE TITLE
Bug: alarm can be stopped without scanning QR code

### ISSUE THREAD

**Issue by radiden** [sweakpl/qralarm-android#23]
If you snooze the alarm, you can exit the app, go into its app info in the Android settings and force stop the app, which will disable the alarm

Tested on a Pixel 6 running the Android 14 beta

![image](https://user-images.githubusercontent.com/28237353/235009345-e15ad4f8-b1aa-4a42-903d-7ba764d49fa1.png)

**Comment by sweakpl** [comment]
This "issue" has already been mentioned in https://github.com/sweakpl/qralarm-android/issues/20. Please, refer to this thread.
