### ISSUE TITLE
Support for Multiple, distinct Alarms - Scheduling

### ISSUE THREAD

**Issue by tearfulnumpty** [sweakpl/qralarm-android#24]
QR Alarm should allow for support of multiple distinct alarms.  For example, if I wanted an alarm to be scheduled daily at 8 AM, and nightly at 10 PM, I shouldn't have to reset and change my alarms twice, daily.  

It would be nice to merely have these set as a given schedule, and even nicer if it had advanced scheduling techniques allowing for it to repeat on specific weekdays, etc.

**Comment by sweakpl** [comment]
Hey, this issue has been already touched upon in https://github.com/sweakpl/qralarm-android/issues/5 and https://github.com/sweakpl/qralarm-android/issues/2 threads. This feature is not planned to be added now but may be considered in the future.

**Comment by tearfulnumpty** [comment]
Those issues only mention scheduled and persistent alarms, but not multiple simultaneous alarms.  I believe the functionality of my first paragraph is distinct from scheduling, though my second paragraph included scheduling since it's a related topic.  

Even looking past the possibility of scheduling as an explicit option with prompts to the user, warning them of the perceived risks, simply having a second alarm which can be set at the same time as the first in a manual fashion would be beneficial.  As for the first paragraph's example use case, I would currently have to scroll through a not so great sliding system twice a day to set my alarms.  With the proposed feature here, even if I still had to manually enable my alarms daily (without the scheduling addition), I could still have a distinct alarm for the AM and for the PM which would highly mitigate the above problem.  

If multiple alarms are manually configurable and also able to be enabled concurrently, I would also only need to do this manual interaction once a day.  I think this is distinct from #2 and #5, and I would kindly ask you to reconsider.

**Comment by sweakpl** [comment]
I think I understand your case. This is a compromise between alarm scheduling and safety. I like that idea and can see it working although I can not guarantee if and when such feature would be added to the application as it seems to me that it requires some major restructuring in the code. Thank you for contributing either way!

**Comment by tearfulnumpty** [comment]
Just wanted to pop in and say thanks!  I really appreciate this feature being added!
