### ISSUE TITLE
Notification when Alarm is set

### ISSUE THREAD

**Issue by tearfulnumpty** [sweakpl/qralarm-android#25]
A notification bar should be configurable when an alarm is present.  For example, if I have an alarm set at 10 PM, some X time (maybe hours in 0.5 hour intervals) before my alarm is scheduled to go off, it would be nice to see a notification of said alarm on my phone.  

A major reason for this is not only reminders relating to the alarm itself, but also the ability to take care of the alarm early if applicable.  Say you set an alarm to do something at 10 PM, and it's currently 9:50 PM.  You've already done the task, and you want to go ahead and disable the alarm properly via QR scan.  Without a notification of the alarm, the user must unlock the phone, open the QR app, etc, in a more tedious process.  With a notification, a simple click could pull up the alarm deactivation panel without unlocking, similarly to how the alarm itself normally goes off.

**Comment by sweakpl** [comment]
Thank you! This is a good idea, I will consider it in the future.
