### ISSUE TITLE
Support for setting this as default clock application

### ISSUE THREAD

**Issue by Minibus93** [sweakpl/qralarm-android#26]
Hello, basically title

I would love to have the possibility of choosing this as default clock app so that launcher like Olauncher and other apps in general would give me the option to set QRalarm as default clock application!

**Comment by sweakpl** [comment]
I'm not exactly sure what you mean. As far as I know Android lets users choose default apps for calling, internet browsing etc. but not for setting alarms. Android settings have this page for default applications and there seems to be no way of setting a default alarm clock application:

![default-apps-settings](https://github.com/sweakpl/qralarm-android/assets/70141120/ad6261f2-6f15-4d81-aec3-4e0f4e4aef37)

**Comment by Minibus93** [comment]
I'm sorry if my explaination was lackluster. English is not my primary language so I may struggle a bit.

I'll explain better:

I'm using Olauncher as my phone launcher. It's a bit hard to explain to someone who may not know this app, but it has a feature that if you click on the time showed on the homepage there, it allows you to open the clock app.

According to [this answer of Olauncher dev](https://github.com/tanujnotes/Olauncher/issues/175) he says that if you have multiple clock apps, it should prompt you to pick which clock to open (ES. just like the prompt you see when you re in a file manager, click on a picture and it tells you to choose with which app you want to see the photo, the gallery or the file manager photo viewer)

Since I have both the default Xiaomi clock app and QRalarm, I assumed such a prompt should've appear. Due to the launcher dev response in the issue linked I thought it could be an "issue" on QRalarm end and tried to open an issue here to report the situation.

I hope this explains better and I'm sorry if my thoughts were wrong and this is not on QRalarm.

**Comment by sweakpl** [comment]
Thank you for clarification! I've looked into the code of Olauncher and probably found the reason to why QRAlarm is not listed as an available alarm clock. I will try to fix the issue as soon as I get my hands on the code.

**Comment by Minibus93** [comment]
Just wanted to confirm that it's now showing up and working in 1.4.1!

Really appreciate you looking and going into this! ♥️
