### ISSUE TITLE
cant change alarm music

### ISSUE THREAD

**Issue by beastr45** [sweakpl/qralarm-android#29]
currently the alarm music selection is very linited, adding more default ringtones wlild be great. the feature to add custom ringtones is broken and dosent work.

when opening a ringtone that is custom nothing happens. the app dosent seem to want any file permissions unsure how to make the apps ringtone selector functional with normal android.

**Comment by sweakpl** [comment]
Hey, I've tested with latest clean Android and couldn't reproduce the issue - selecting custom ringtone works fine. This might be a specific custom ROM issue. Can you please provide more information on your device's Android version, manufacturer and ROM? I might get my hands on a similar device and try to reproduce and fix the problem.

**Comment by beastr45** [comment]
hi i have the android kernel versoon 4.19 and my phone has knox which i can  not uninstall. my device has the rom used for samsung phones. my phones model is the samsung s20 se. I am not shure if the problem is caused by a security feature regarding reading and writing files because other apps have been hindered due to the app permissions. I think that other alarm apps have just pulled all of the ringtones using some sort of ringtone library, being able to use default samsung ring tones would be nice because that is the only reason my problem exists in the first place.

**Comment by beastr45** [comment]
> currently the alarm music selection is very linited, adding more default ringtones wlild be great. the feature to add custom ringtones is broken and dosent work.
> 
> when opening a ringtone that is custom nothing happens. the app dosent seem to want any file permissions unsure how to make the apps ringtone selector functional with normal android.



> Hey, I've tested with latest clean Android and couldn't reproduce the issue - selecting custom ringtone works fine. This might be a specific custom ROM issue. Can you please provide more information on your device's Android version, manufacturer and ROM? I might get my hands on a similar device and try to reproduce and fix the problem.

hi i have the android kernel versoon 4.19 and my phone has knox which i can not uninstall. my device has the rom used for samsung phones. my phones model is the samsung s20 se. I am not shure if the problem is caused by a security feature regarding reading and writing files because other apps have been hindered due to the app permissions. I think that other alarm apps have just pulled all of the ringtones using some sort of ringtone library, being able to use default samsung ring tones would be nice because that is the only reason my problem exists in the first place.

**Comment by sweakpl** [comment]
I have just tested the feature of adding custom ringtones on a non-rooted Samsung S21 FE with default ROM and it works just fine. Seems like the Samsung Knox platform might be interfering with the storage access of QRAlarm. When it comes to setting the default system ringtone, this feature was already implemented but scrapped later as it was causing crashes on the phones lacking default ringtones (the problem was covered in the issue #1). I must admit, this decision was probably too hasty and I could've handled it differently. I will keep in mind this issue and, when appropriate, try to bring the functionality back to the app.
