### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by shuvashish76** [sweakpl/qralarm-android#3]
Would be nice to have this app on F-Droid.

Currently available on [izzy repo](https://apt.izzysoft.de/fdroid/index/apk/com.sweak.qralarm)

**Comment by sweakpl** [comment]
The issue on F-Droid has been created: https://gitlab.com/fdroid/rfp/-/issues/2229

**Comment by shuvashish76** [comment]
Live on F-Droid: https://www.f-droid.org/packages/com.sweak.qralarm/

**Comment by sweakpl** [comment]
Yes, the app can stay in your repo, that is fine 😃

**Comment by IzzySoft** [comment]
OK, marking it that way then (so it doesn't show up in the "todo reports" anymore). Thanks!
