### ISSUE TITLE
multiple alarms?

### ISSUE THREAD

**Issue by useless642** [sweakpl/qralarm-android#30]
hi, can you please considerer implementing multiple alarms?

this is the only FOSS clock alarm app that has QR implemented, but having only 1 alarm completely defeats the purpose of it :(

can you please considerer implementing that?

**Comment by sweakpl** [comment]
Hey, this topic has been touched upon in #24 and I still have it in mind.

**Comment by useless642** [comment]
I can help with testing, if you need someone.

**Comment by ARedGuy** [comment]
App really needs this feature
