### ISSUE TITLE
Follow system theme

### ISSUE THREAD

**Issue by xmha97** [sweakpl/qralarm-android#31]
Please add light theme and then follow system theme.
Thanks 🙏

**Comment by sweakpl** [comment]
QRAlarm was actually never created with dark mode in mind - it just has a single primary color palette which just happens to be more dark than light. Sorry, but the feature you are requesting is likely not going to be considered.

**Comment by sweakpl** [comment]
QRAlarm was actually never created with dark mode in mind - it just has a single primary color palette which just happens to be more dark than light. Sorry, but the feature you are requesting is likely not going to be considered.
