### ISSUE TITLE
Alarm after second snooze won't go off

### ISSUE THREAD

**Issue by KnockoffFeline** [sweakpl/qralarm-android#32]
After I snooze the alarm the second time, the app will miss the schedule and not trigger the alarm. This issue is mostly reproducible on my device (Redmi Note 11 Pro 5G running Android 13), but not completely.

Here are my settings, in case it is of any help:
![Screenshot_2023-11-22-06-58-00-335_com sweak qralarm](https://github.com/sweakpl/qralarm-android/assets/62443058/79f941d9-cdcd-4f63-aa22-3ab41f024b4e)

**Comment by sweakpl** [comment]
Hey, I couldn't get my hands on your particular device, but I have tested with the same settings on my devices and couldn't reproduce the issue. Are you sure that you have disabled the battery optimizations for QRAlarm? The guide in the app settings specifically mentions [dontkillmyapp.com](https://dontkillmyapp.com/) website - it contains instructions on how to disable battery optimizations for the app which may be causing QRAlarm to malfunction.
