### ISSUE TITLE
can't stop the alarm without a qr code

### ISSUE THREAD

**Issue by osowiecki** [sweakpl/qralarm-android#35]
Give me a way to disable the alarm right before it fires and without a QR code...

**Comment by sweakpl** [comment]
There is an option in the settings to allow disabling the alarm without the QR code up to 1 hour before the alarm time. I wouldn't allow disabling the alarm right before it fires because it would defeat the purpose of the app, wouldn't it? The alarm is supposed to get you up, not only wake you up.
