### ISSUE TITLE
Bug: Vibrations stops after two seconds if phone is upside down

### ISSUE THREAD

**Issue by mizzunet** [sweakpl/qralarm-android#36]
Steps to reproduce
1. Set an alarm and enable vibration
2. Put phone upside down(front side below)
3. Wait till  alarm plays
4. See the vibration stops after two seconds

Thanks

**Comment by sweakpl** [comment]
It might be the case that it isn't a bug in the application itself but rather a system feature. Here's an example of such feature on Google Pixel devices:

> **Flip to Shhh**
> To quickly turn on Do Not Disturb, place your phone face down on a flat surface.

https://support.google.com/pixelphone/answer/7443425?hl=en&sjid=5588784527499718907-EU#flip_to_shhh&zippy=%2Csee-how-to-place-your-phone-face-down

I couldn't reporoduce the issue on my devices unfortunately.
