### ISSUE TITLE
Timer feature

### ISSUE THREAD

**Issue by Vilhelm-Ian** [sweakpl/qralarm-android#38]
I have a qr code near my dumbells. I want to set a timer that will require me to scan the qr code so I will be forced to return to the dumbells after the break between my sets is over.

I can use the current feature in the following manner. Set an alarm for current time + minutes my break lasts. But that's more cumberstone than just having an option to press one button that will start a timer for predefined minutes.

I already open an issue for this. But couldn't find my issue so I thought maybe I forgot to press the submit button

**Comment by sweakpl** [comment]
Sorry, but the application is designed as a rather single-purpose tool and integrating a timer does not really align with what the app idea is (an alarm clock - not a timer). Second of all, introducing such a specific feature requires me to introduce the feature to all the existing users but I want the app to be suited for everyone and not filled with very custom functionalities that only a few people would use or even understand.
