### ISSUE TITLE
Silence alarm temporarily when pressing stop

### ISSUE THREAD

**Issue by Commenter25** [sweakpl/qralarm-android#41]
This is the only missing feature preventing me from migrating from Sleep as Android (a proprietary paid app) to this. In that app, when you press stop, it silences the alarm for 60 seconds to give you time to scan the QR.

As I live with others, I like having the gentle wakeup only go as loud as needed to get me awake, pressing stop ASAP so nobody hears it, then I rush out to scan the QR. Having a alarm blaring as I'm trying to scan is not ideal. Obviously, after the 60 second timeout, it should start playing the alarm sound again so it isn't just a get out of jail free card.

**Comment by sweakpl** [comment]
Hey, this is a great idea! I will give it a closer look when preparing the next update.

**Comment by mozilla2012** [comment]
I agree with OP that this would be a lovely feature, but making this an optional setting would be preferred 🙂

**Comment by Commenter25** [comment]
15 seconds is quite a short duration. Perhaps this should be adjustable?

That said, thank you for implementing it ^^
