### ISSUE TITLE
Android 15: cannot turn on flash when scanning QR code because of new edge-to-edge feature

### ISSUE THREAD

**Issue by anandv96** [sweakpl/qralarm-android#47]
After upgrading my phone to android 15, I cannot turn on the flash light/torch when I scan a QR code. The lightning bolt icon to turn on the flash is stuck behind the android system clock.

This seems to be caused by the new enforced edge-to-edge feature on android 15. Here's a guide on how to deal with this from the Android Developers team at Google: https://medium.com/androiddevelopers/insets-handling-tips-for-android-15s-edge-to-edge-enforcement-872774e8839b

**Comment by sweakpl** [comment]
Thank you for reporting, I will definitely tackle this as soon as I can.
