### ISSUE TITLE
Feature request: skip next scheduled alarm

### ISSUE THREAD

**Issue by finn-wa** [sweakpl/qralarm-android#52]
When I have a repeating scheduled alarm, sometimes I'd like to skip the next instance without disabling the alarm entirely.

e.g. if it's a public holiday on Monday, I want to be able to skip one instance of my weekday alarm without needing to remember to re-enable it in time for work on Tuesday.

Thanks for your work on the app, it's such a breath of fresh air after the enshittification of Alarmy!

**Comment by sweakpl** [comment]
Thank you for your feedback!

This option is already available since version 2.1 - make sure to update 😀

**Comment by finn-wa** [comment]
incredible!
