### ISSUE TITLE
Bug: 1h-before-alarm-disable-gate not working as intended

### ISSUE THREAD

**Issue by noerw** [sweakpl/qralarm-android#53]
See attached screenshot. >1h until the alarm, but i can't disable it without QR-code.
Not sure what the blocked interval before alarm is, but its more than an hour as indicated in the tooltip.

Using fdroid build 2.0.5 (but observed the described behaviour also in earlier releases)

<img src="https://github.com/user-attachments/assets/c88557d3-406a-4f02-819b-15b93efce87a" width="50%" />

btw, amazing app, thanks so much!

fwiw, my phone timezone is UTC+1, maybe that's it.

**Comment by sweakpl** [comment]
Thanks for the feedback! 

This issue has been fixed in the 2.1 version. Make sure to update to the latest one 😀
