### ISSUE TITLE
Feature Request: Reminder to set alarm for next day

### ISSUE THREAD

**Issue by trymeouteh** [sweakpl/qralarm-android#6]
Please add a setting which will give the user a notification reminder to set the alarm for the next day. The setting will decide weather this will be enabled and what time in the day the notification will go off.

This way the user will never forget to set their alarm.

**Comment by sweakpl** [comment]
Thanks, this idea is very clever. I will consider it and perhaps in the future you will find it in the actual app. As for now I'm on a tight schedule with work and uni, but as soon as I get my hands back on QRAlarm i will try to implement your idea.
