### ISSUE TITLE
Feature Request: Set custom audio file as alarm sound

### ISSUE THREAD

**Issue by magnus-ISU** [sweakpl/qralarm-android#7]
#1 makes it sound like this used to exist. I think the 3 default sounds are trash so I hope this is added.

If its not I'll probably do it myself.

**Comment by magnus-ISU** [comment]
Mostly got this working but somehow android is doing something weird and not using my custom URI. Random question, is there a way to do 'debug printing' in android? Do you just make a bunch of toasts?

**Comment by sweakpl** [comment]
Yes, You can use Android [logging API](https://developer.android.com/reference/android/util/Log) to send logs and debug. You can see the logs in the Logcat via Android Studio or ADB.

**Comment by magnus-ISU** [comment]
Done in #8
